service: email

# provider:
#   name: aws
#   runtime: nodejs10.16

functions:
  portfolioMailer:
    handler: handler.portfolioMailer
    events:
      - http:
          method: post
          path: portfolio-mailer
          cors: true

provider:
  name: aws
  runtime: nodejs10.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: ["*"]